logging:
  file:
    path: logs
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  main:
    banner-mode: off
    web-application-type: none
  shell:
    interactive:
      enabled: true
    script:
      enabled: true